### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by wrl1224** [jaywalnut310/vits#146]
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "D:\Anaconda3\envs\vits\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "D:\AiPoject\vits-main\train.py", line 71, in run
    train_dataset = TextAudioLoader(hps.data.training_files, hps.data)
  File "D:\AiPoject\vits-main\data_utils.py", line 38, in __init__
    self._filter()
  File "D:\AiPoject\vits-main\data_utils.py", line 51, in _filter
    for audiopath, text in self.audiopaths_and_text:
ValueError: too many values to unpack (expected 2)

**Comment by wrl1224** [comment]
Why is that?

**Comment by JunhaoHuang0615** [comment]
same problem, have you solved it?

**Comment by dvsonic** [comment]
check your filelist ,you may find some extra "|"  which should be remove
