### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by YTRemRem** [jaywalnut310/vits#162]
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "C:\Users\rem\anaconda3\envs\vits\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "F:\AI Voice (VITS - SoVITS)\vits orig\train.py", line 117, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler, [train_loader, eval_loader], logger, [writer, writer_eval])
  File "F:\AI Voice (VITS - SoVITS)\vits orig\train.py", line 137, in train_and_evaluate
    for batch_idx, (x, x_lengths, spec, spec_lengths, y, y_lengths) in enumerate(train_loader):
  File "C:\Users\rem\anaconda3\envs\vits\lib\site-packages\torch\utils\data\dataloader.py", line 633, in __next__
    data = self._next_data()
  File "C:\Users\rem\anaconda3\envs\vits\lib\site-packages\torch\utils\data\dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "C:\Users\rem\anaconda3\envs\vits\lib\site-packages\torch\utils\data\dataloader.py", line 1371, in _process_data
    data.reraise()
  File "C:\Users\rem\anaconda3\envs\vits\lib\site-packages\torch\_utils.py", line 644, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\rem\anaconda3\envs\vits\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\rem\anaconda3\envs\vits\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\rem\anaconda3\envs\vits\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "F:\AI Voice (VITS - SoVITS)\vits orig\data_utils.py", line 94, in __getitem__
    return self.get_audio_text_pair(self.audiopaths_and_text[index])
  File "F:\AI Voice (VITS - SoVITS)\vits orig\data_utils.py", line 62, in get_audio_text_pair
    spec, wav = self.get_audio(audiopath)
  File "F:\AI Voice (VITS - SoVITS)\vits orig\data_utils.py", line 76, in get_audio
    spec = spectrogram_torch(audio_norm, self.filter_length,
  File "F:\AI Voice (VITS - SoVITS)\vits orig\mel_processing.py", line 66, in spectrogram_torch
    spec = torch.stft(y, n_fft, hop_length=hop_size, win_length=win_size, window=hann_window[wnsize_dtype_device],
  File "C:\Users\rem\anaconda3\envs\vits\lib\site-packages\torch\functional.py", line 641, in stft
    return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
RuntimeError: stft requires the return_complex parameter be given for real inputs, and will further require that return_complex=True in a future PyTorch release.

**Comment by JasonBlain** [comment]
@YTRemRem how did you resolve this?

I'm between that error in python 3.10.12 and a dimension out of range in 3.8

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/mnt/d/Users/BLAIN/vits/bjSpeech/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 68, in _wrap
    fn(i, *args)
  File "/mnt/d/Users/BLAIN/vits/train.py", line 118, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler, [train_loader, eval_loader], logger, [writer, writer_eval])
  File "/mnt/d/Users/BLAIN/vits/train.py", line 138, in train_and_evaluate
    for batch_idx, (x, x_lengths, spec, spec_lengths, y, y_lengths) in enumerate(train_loader):
  File "/mnt/d/Users/BLAIN/vits/bjSpeech/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/mnt/d/Users/BLAIN/vits/bjSpeech/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/mnt/d/Users/BLAIN/vits/bjSpeech/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/mnt/d/Users/BLAIN/vits/bjSpeech/lib/python3.8/site-packages/torch/_utils.py", line 722, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/mnt/d/Users/BLAIN/vits/bjSpeech/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/mnt/d/Users/BLAIN/vits/bjSpeech/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/mnt/d/Users/BLAIN/vits/data_utils.py", line 114, in __call__
    torch.LongTensor([x[1].size(1) for x in batch]),
  File "/mnt/d/Users/BLAIN/vits/data_utils.py", line 114, in <listcomp>
    torch.LongTensor([x[1].size(1) for x in batch]),
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

**Comment by Nathanael-Tardy** [comment]
I'm getting the same error, how did you fix it @YTRemRem ?

**Comment by ZodiacFRA** [comment]
I'm getting the same error, how did you fix it @YTRemRem ?

**Comment by YTRemRem** [comment]
It's been a while, I have forgotten how to solve it, sorry for that.

**Comment by akayuki39** [comment]
I encountered this error and solved it (according https://github.com/s3prl/s3prl/issues/475#issuecomment-1713117284) by changing all the
```
spec = torch.stft(y, n_fft, hop_length=hop_size, win_length=win_size, window=hann_window[wnsize_dtype_device],
                      center=center, pad_mode='reflect', normalized=False, onesided=True)
```
in file `mel_processing.py` into 
```
spec = torch.stft(y, n_fft, hop_length=hop_size, win_length=win_size, window=hann_window[wnsize_dtype_device],
                      center=center, pad_mode='reflect', normalized=False, onesided=True, return_complex=False)
```
