### ISSUE TITLE
having numpy complex error

### ISSUE THREAD

**Issue by M-Usamah** [jaywalnut310/vits#199]
/envs/testVits/bin/python /media/usamah/2AAD843B4D4DD7CD/projects/vits/test.py
Traceback (most recent call last):
  File "/media/usamah/2AAD843B4D4DD7CD/projects/vits/test.py", line 14, in <module>
    from vit_model.data_utils import TextAudioLoader, TextAudioCollate, TextAudioSpeakerLoader, TextAudioSpeakerCollate
  File "/media/usamah/2AAD843B4D4DD7CD/projects/vits/vit_model/data_utils.py", line 9, in <module>
    from vit_model.mel_processing import spectrogram_torch
  File "/media/usamah/2AAD843B4D4DD7CD/projects/vits/vit_model/mel_processing.py", line 9, in <module>
    import librosa
  File "/home/usamah/anaconda3/envs/testVits/lib/python3.10/site-packages/librosa/__init__.py", line 211, in <module>
    from . import core
  File "/home/usamah/anaconda3/envs/testVits/lib/python3.10/site-packages/librosa/core/__init__.py", line 9, in <module>
    from .constantq import *  # pylint: disable=wildcard-import
  File "/home/usamah/anaconda3/envs/testVits/lib/python3.10/site-packages/librosa/core/constantq.py", line 1058, in <module>
    dtype=np.complex,
  File "/home/usamah/anaconda3/envs/testVits/lib/python3.10/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'complex'.
`np.complex` was a deprecated alias for the builtin `complex`. To avoid this error in existing code, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'complex_'?
    
 I am running this on python=3.10 which have numpy version of 1.26.2

**Comment by mac819** [comment]
I also faced same issue. Possibly this is happening due to numpy version conflict. To skip this issue, overwriting the file: /home/usamah/anaconda3/envs/testVits/lib/python3.10/site-packages/librosa/core/constantq.py on line 1058 **np.complex** >> **complex**.
This will import the modules without any error.
