### ISSUE TITLE
Can't install requirement

### ISSUE THREAD

**Issue by zhouhao27** [jaywalnut310/vits#209]
When I run:

> pip install -r requirements.txt

I got the following error:

>   × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      Running from numpy source directory.
      <string>:461: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      /tmp/pip-install-1epas1ab/numpy_c2b59e3e8dda400cbcb9eb4923ea6727/tools/cythonize.py:75: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        required_version = LooseVersion('0.29.14')
      /tmp/pip-install-1epas1ab/numpy_c2b59e3e8dda400cbcb9eb4923ea6727/tools/cythonize.py:77: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        if LooseVersion(cython_version) < required_version:
      
>      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          def __init__(self, seed=None):
              BitGenerator.__init__(self, seed)
              self.rng_state.pcg_state = &self.pcg64_random_state
      
              self._bitgen.state = <void *>&self.rng_state
              self._bitgen.next_uint64 = &pcg64_uint64
                                         ^
      ------------------------------------------------------------
      
>      _pcg64.pyx:113:35: Cannot assign type 'uint64_t (*)(void *) except? -1 nogil' to 'uint64_t (*)(void *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to the type of the value being assigned.
      Processing numpy/random/_bounded_integers.pxd.in
      Processing numpy/random/_pcg64.pyx
      Traceback (most recent call last):
        File "/tmp/pip-install-1epas1ab/numpy_c2b59e3e8dda400cbcb9eb4923ea6727/tools/cythonize.py", line 238, in <module>
          main()
        File "/tmp/pip-install-1epas1ab/numpy_c2b59e3e8dda400cbcb9eb4923ea6727/tools/cythonize.py", line 234, in main
          find_process_files(root_dir)
        File "/tmp/pip-install-1epas1ab/numpy_c2b59e3e8dda400cbcb9eb4923ea6727/tools/cythonize.py", line 225, in find_process_files
          process(root_dir, fromfile, tofile, function, hash_db)
        File "/tmp/pip-install-1epas1ab/numpy_c2b59e3e8dda400cbcb9eb4923ea6727/tools/cythonize.py", line 191, in process
          processor_function(fromfile, tofile)
        File "/tmp/pip-install-1epas1ab/numpy_c2b59e3e8dda400cbcb9eb4923ea6727/tools/cythonize.py", line 80, in process_pyx
          subprocess.check_call(
        File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/home/zeus/miniconda3/envs/cloudspace/bin/python', '-m', 'cython', '-3', '--fast-fail', '-o', '_pcg64.c', '_pcg64.pyx']' returned non-zero exit status 1.
      Cythonizing sources
      Traceback (most recent call last):
        File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-3q02jch8/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 366, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-3q02jch8/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-3q02jch8/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 488, in <module>
        File "<string>", line 469, in setup_package
        File "<string>", line 275, in generate_cython
      RuntimeError: Running cythonize failed!
      [end of output]
  
>  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

> × Encountered error while generating package metadata.
╰─> See above for output.

> note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

My python is 3.10.10. Any idea? Thanks.

**Comment by zhouhao27** [comment]
I python 3.6.10 solve the issue.
