### ISSUE TITLE
Code doesn;t even run. so many errors intalling pip

### ISSUE THREAD

**Issue by thenaivekid** [jaywalnut310/vits#213]
Collecting Cython==0.29.21 (from -r requirements.txt (line 1))
  Using cached Cython-0.29.21-py2.py3-none-any.whl (974 kB)
Collecting librosa==0.8.0 (from -r requirements.txt (line 2))
  Using cached librosa-0.8.0.tar.gz (183 kB)
  Preparing metadata (setup.py) ... done
Collecting matplotlib==3.3.1 (from -r requirements.txt (line 3))
  Using cached matplotlib-3.3.1.tar.gz (38.8 MB)
  Preparing metadata (setup.py) ... done
Collecting numpy==1.18.5 (from -r requirements.txt (line 4))
  Using cached numpy-1.18.5.zip (5.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by phigrey** [comment]
I have encountered the same error when using Colab, but not on my desktop.
In my  case using Colab, after `git clone`, I have removed all the version information in `requirements.txt`, only leaving the package names.

**Comment by tusharhchauhan** [comment]
this code is working on pytorch 2.1 with latest libraries, which are :
```
torch==2.1.2
unidecode==1.3.8
tensorboard==2.13
protobuff==3.20
librosa==0.10.1
phonemizer==3.2.1
cython==3.0.10
```
install these dependencies and run.

**Comment by jellehak** [comment]
> this code is working on pytorch 2.1 with latest libraries, which are : torch = 2.1.2 unidecode = 1.3.8 tensorboard = 2.13 protobuff = 3.20 librosa = 0.10.1 phonemizer = 3.2.1 cython=3.0.10 install these dependencies and run.

Worked great, PR maybe?

**Comment by death178** [comment]
you had just a typo in there, it is:
`torch==2.1.2`
`unidecode==1.3.8`
`tensorboard==2.13`
`protobuf==3.20`
`librosa==0.10.1`
`phonemizer==3.2.1`
`cython==3.0.10`

**Comment by pclpp** [comment]
still have problem with 
Name: torch
Version: 2.1.2
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /home/jerry/miniconda3/envs/vits_tor212/lib/python3.8/site-packages
Requires: filelock, fsspec, jinja2, networkx, nvidia-cublas-cu12, nvidia-cuda-cupti-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-runtime-cu12, nvidia-cudnn-cu12, nvidia-cufft-cu12, nvidia-curand-cu12, nvidia-cusolver-cu12, nvidia-cusparse-cu12, nvidia-nccl-cu12, nvidia-nvtx-cu12, sympy, triton, typing-extensions
Required-by:
  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
Mon Aug 26 18:01:56 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.42.02              Driver Version: 555.42.02      CUDA Version: 12.5     |
|-----------------------------------------+------------------------+---------------------
=========================================+========================+======================|
|   0  NVIDIA A40                     Off |   00000000:01:00.0 Off |                    0 |
|  0%   31C    P8             24W /  300W |       1MiB /  46068MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
../aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [105,0,0], thread: [30,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [105,0,0], thread: [31,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Traceback (most recent call last):
  File "train_ms.py", line 294, in <module>
    main()
  File "train_ms.py", line 50, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "/home/jerry/miniconda3/envs/vits_tor212/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 246, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
  File "/home/jerry/miniconda3/envs/vits_tor212/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 202, in start_processes
    while not context.join():
  File "/home/jerry/miniconda3/envs/vits_tor212/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 145, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with signal SIGABRT

[erro_torch_212.txt](https://github.com/user-attachments/files/16747223/erro_torch_212.txt)

**Comment by HenraL** [comment]
You have an error in your dependencies
As of writing this post, event the tensorflow (if run from scracth) will fail to install the depedencies.
This is the error:

```bash
git clone https://github.com/jaywalnut310/vits.git

Cloning into 'vits'...
remote: Enumerating objects: 81, done.
remote: Total 81 (delta 0), reused 0 (delta 0), pack-reused 81 (from 1)
Receiving objects: 100% (81/81), 3.33 MiB | 13.60 MiB/s, done.
Resolving deltas: 100% (22/22), done.

cd vits
/content/vits

pip install -r requirements.txt
Collecting Cython==0.29.21 (from -r requirements.txt (line 1))
  Downloading Cython-0.29.21-py2.py3-none-any.whl.metadata (2.6 kB)
Collecting librosa==0.8.0 (from -r requirements.txt (line 2))
  Downloading librosa-0.8.0.tar.gz (183 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.9/183.9 kB 4.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting matplotlib==3.3.1 (from -r requirements.txt (line 3))
  Downloading matplotlib-3.3.1.tar.gz (38.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.8/38.8 MB 21.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting numpy==1.18.5 (from -r requirements.txt (line 4))
  Downloading numpy-1.18.5.zip (5.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 54.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by xora-17** [comment]
This is due to outdated versions of libraries. Just remove version numbers from requirements. Note that you may have to resolve some dependency issues.

requirement.txt
```
Cython
librosa
numpy
matplotlib
phonemizer
scipy
tensorboard
torch
torchvision
Unidecode
```
