### ISSUE TITLE
Can't train with fp16 on Nvidia RTX3060 

### ISSUE THREAD

**Issue by thangnvkcn** [jaywalnut310/vits#45]
training with fp16 doesn't work for me on a RTX3060, I'll look into fixing it, but for future reference here is the full stacktrace
torch version 1.9.0

INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for 1 nodes.
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCCachingHostAllocator.cpp line=278 error=710 : device-side assert triggered
terminate called after throwing an instance of 'std::runtime_error'
  what():  NCCL error in: /pytorch/torch/lib/c10d/../c10d/NCCLUtils.hpp:158, unhandled cuda error, NCCL version 2.7.8
ncclUnhandledCudaError: Call to CUDA function failed.

RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by nikich340** [comment]
maybe problem in too new torch version, have you tried 1.8.1+cu111 ?

**Comment by Dragon1573** [comment]
I'm currently running the project inside **Docker Desktop for Windows** with **WSL2 Backend** enabled and `docker run --gpus all` switches attatched.

All logs are attached as follows.

<details><summary>GPU Information</summary>

```text
(.venv) root@a77fd2165454:/workspaces/vits# nvidia-smi
Fri Nov 29 17:18:53 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 565.57.02              Driver Version: 566.03         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 2070        On  |   00000000:01:00.0  On |                  N/A |
|  0%   55C    P0             29W /  131W |    1812MiB /   8192MiB |      1%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A        33      G   /Xwayland                                   N/A      |
+-----------------------------------------------------------------------------------------+
```

</details>

<details><summary>NVIDIA-related packages in <code>apt</code></summary>

```text
(.venv) root@a77fd2165454:/workspaces/vits# apt list '*nvidia*'
Listing... Done
boinc-client-nvidia-cuda/oldstable 7.16.16+dfsg-1 amd64
bumblebee-nvidia/oldstable 3.2.1-27 amd64
firmware-nvidia-gsp/unknown 560.35.05-1 amd64
glx-alternative-nvidia/oldstable 1.2.1~deb11u1 amd64
hashcat-nvidia/oldstable 20210201 all
libegl-nvidia0/unknown 560.35.05-1 amd64
libegl-nvidia0/unknown 560.35.05-1 i386
libegl1-nvidia/unknown 555.42.06-1 amd64
libgl1-nvidia-glvnd-glx/unknown 560.35.05-1 amd64
libgl1-nvidia-glvnd-glx/unknown 560.35.05-1 i386
libgles-nvidia1/unknown 560.35.05-1 amd64
libgles-nvidia1/unknown 560.35.05-1 i386
libgles-nvidia2/unknown 560.35.05-1 amd64
libgles-nvidia2/unknown 560.35.05-1 i386
libglx-nvidia0/unknown 560.35.05-1 amd64
libglx-nvidia0/unknown 560.35.05-1 i386
libnvidia-allocator1/unknown 560.35.05-1 amd64
libnvidia-allocator1/unknown 560.35.05-1 i386
libnvidia-api1/unknown 560.35.05-1 amd64
libnvidia-cfg1/unknown 560.35.05-1 amd64
libnvidia-compiler/unknown 530.30.02-1 amd64
libnvidia-compiler/unknown 530.30.02-1 i386
libnvidia-container-dev/unknown 1.17.2-1 amd64
libnvidia-container-tools/unknown 1.17.2-1 amd64
libnvidia-container1-dbg/unknown 1.17.2-1 amd64
libnvidia-container1/unknown 1.17.2-1 amd64
libnvidia-egl-wayland-dev/oldstable 1:1.1.5-1 amd64
libnvidia-egl-wayland1/oldstable 1:1.1.5-1 amd64
libnvidia-egl-xcb1/unknown 560.35.05-1 amd64
libnvidia-egl-xcb1/unknown 560.35.05-1 i386
libnvidia-egl-xlib1/unknown 560.35.05-1 amd64
libnvidia-egl-xlib1/unknown 560.35.05-1 i386
libnvidia-eglcore/unknown 560.35.05-1 amd64
libnvidia-eglcore/unknown 560.35.05-1 i386
libnvidia-encode1/unknown 560.35.05-1 amd64
libnvidia-encode1/unknown 560.35.05-1 i386
libnvidia-fbc1/unknown 560.35.05-1 amd64
libnvidia-fbc1/unknown 560.35.05-1 i386
libnvidia-glcore/unknown 560.35.05-1 amd64
libnvidia-glcore/unknown 560.35.05-1 i386
libnvidia-glvkspirv/unknown 560.35.05-1 amd64
libnvidia-glvkspirv/unknown 560.35.05-1 i386
libnvidia-gpucomp1/unknown 555.42.06-1 amd64
libnvidia-gpucomp1/unknown 555.42.06-1 i386
libnvidia-gpucomp/unknown 560.35.05-1 amd64
libnvidia-gpucomp/unknown 560.35.05-1 i386
libnvidia-ml1/unknown 560.35.05-1 amd64
libnvidia-ml1/unknown 560.35.05-1 i386
libnvidia-ngx1/unknown 560.35.05-1 amd64
libnvidia-nscq-495/unknown 495.29.05-1 amd64
libnvidia-nscq-510/unknown 510.84-1 amd64
libnvidia-nscq-515/unknown 515.105.01-1 amd64
libnvidia-nscq-520/unknown 520.61.05-1 amd64
libnvidia-nscq-525/unknown 525.147.05-1 amd64
libnvidia-nscq-530/unknown 530.30.02-1 amd64
libnvidia-nscq-535/unknown 535.216.03-1 amd64
libnvidia-nscq-545/unknown 545.23.08-1 amd64
libnvidia-nscq-550/unknown 550.127.08-1 amd64
libnvidia-nscq-555/unknown 555.42.06-1 amd64
libnvidia-nscq-560/unknown 560.35.05-1 amd64
libnvidia-nvvm4/unknown 560.35.05-1 amd64
libnvidia-nvvm4/unknown 560.35.05-1 i386
libnvidia-opticalflow1/unknown 560.35.05-1 amd64
libnvidia-opticalflow1/unknown 560.35.05-1 i386
libnvidia-pkcs11/unknown 560.35.05-1 amd64
libnvidia-ptxjitcompiler1/unknown 560.35.05-1 amd64
libnvidia-ptxjitcompiler1/unknown 560.35.05-1 i386
libnvidia-rtcore/unknown 560.35.05-1 amd64
libnvidia-vksc-core/unknown 560.35.05-1 amd64
libnvidia-wayland-client/unknown 555.42.06-1 amd64
mate-sensors-applet-nvidia/oldstable 1.24.1-1 amd64
mir-graphics-drivers-nvidia/oldstable 1.8.0+dfsg1-18 amd64
nvidia-alternative/unknown 560.35.05-1 amd64
nvidia-alternative/unknown 560.35.05-1 i386
nvidia-container-toolkit-base/unknown 1.17.2-1 amd64
nvidia-container-toolkit/unknown 1.17.2-1 amd64
nvidia-cuda-mps/unknown 560.35.05-1 amd64
nvidia-detect/unknown 555.42.06-1 amd64
nvidia-driver-assistant/unknown 0.8.28.02-1 all
nvidia-driver-bin/unknown 560.35.05-1 amd64
nvidia-driver-libs-i386/unknown 555.42.06-1 i386
nvidia-driver-libs/unknown 560.35.05-1 amd64
nvidia-driver-libs/unknown 560.35.05-1 i386
nvidia-driver/unknown 560.35.05-1 amd64
nvidia-egl-common/unknown 560.35.05-1 amd64
nvidia-egl-common/unknown 560.35.05-1 i386
nvidia-egl-icd/unknown 560.35.05-1 amd64
nvidia-egl-icd/unknown 560.35.05-1 i386
nvidia-fabricmanager-495/unknown 495.29.05-1 amd64
nvidia-fabricmanager-510/unknown 510.84-1 amd64
nvidia-fabricmanager-515/unknown 515.105.01-1 amd64
nvidia-fabricmanager-520/unknown 520.61.05-1 amd64
nvidia-fabricmanager-525/unknown 525.147.05-1 amd64
nvidia-fabricmanager-530/unknown 530.30.02-1 amd64
nvidia-fabricmanager-535/unknown 535.216.03-1 amd64
nvidia-fabricmanager-545/unknown 545.23.08-1 amd64
nvidia-fabricmanager-550/unknown 550.127.08-1 amd64
nvidia-fabricmanager-555/unknown 555.42.06-1 amd64
nvidia-fabricmanager-560/unknown 560.35.05-1 amd64
nvidia-fabricmanager-dev-495/unknown 495.29.05-1 amd64
nvidia-fabricmanager-dev-510/unknown 510.84-1 amd64
nvidia-fabricmanager-dev-515/unknown 515.105.01-1 amd64
nvidia-fabricmanager-dev-520/unknown 520.61.05-1 amd64
nvidia-fabricmanager-dev-525/unknown 525.147.05-1 amd64
nvidia-fabricmanager-dev-530/unknown 530.30.02-1 amd64
nvidia-fabricmanager-dev-535/unknown 535.216.03-1 amd64
nvidia-fabricmanager-dev-545/unknown 545.23.08-1 amd64
nvidia-fabricmanager-dev-550/unknown 550.127.08-1 amd64
nvidia-fabricmanager-dev-555/unknown 555.42.06-1 amd64
nvidia-fabricmanager-dev-560/unknown 560.35.05-1 amd64
nvidia-fs-dkms/unknown 2.22.3-1 amd64
nvidia-fs/unknown 2.22.3-1 amd64
nvidia-gds-11-5/unknown 11.5.2-1 amd64
nvidia-gds-11-6/unknown 11.6.2-1 amd64
nvidia-gds-11-7/unknown 11.7.1-1 amd64
nvidia-gds-11-8/unknown 11.8.0-1 amd64
nvidia-gds-12-0/unknown 12.0.1-1 amd64
nvidia-gds-12-1/unknown 12.1.1-1 amd64
nvidia-gds-12-2/unknown 12.2.2-1 amd64
nvidia-gds-12-3/unknown 12.3.2-1 amd64
nvidia-gds-12-4/unknown 12.4.1-1 amd64
nvidia-gds-12-5/unknown 12.5.1-1 amd64
nvidia-gds-12-6/unknown 12.6.3-1 amd64
nvidia-gds/unknown 12.6.3-1 amd64
nvidia-imex-550/unknown 550.127.08-1 amd64
nvidia-imex-560/unknown 560.35.05-1 amd64
nvidia-imex/unknown 560.28.03-1 amd64
nvidia-installer-cleanup/oldstable 20151021+13 amd64
nvidia-kernel-common/oldstable 20151021+13 amd64
nvidia-kernel-dkms/unknown 560.35.05-1 amd64
nvidia-kernel-open-dkms/unknown 560.35.05-1 amd64
nvidia-kernel-open/unknown 560.35.05-1 amd64
nvidia-kernel-source/unknown 560.35.05-1 amd64
nvidia-kernel-support/unknown 560.35.05-1 amd64
nvidia-legacy-check/unknown 555.42.06-1 amd64
nvidia-libopencl1/unknown 560.35.05-1 amd64
nvidia-libopencl1/unknown 560.35.05-1 i386
nvidia-modprobe/unknown 560.35.05-1 amd64
nvidia-nonglvnd-vulkan-common/unknown 555.42.06-1 amd64
nvidia-nonglvnd-vulkan-common/unknown 555.42.06-1 i386
nvidia-open-560.28.03/unknown 560.28.03 amd64
nvidia-open-560.35.03/unknown 560.35.03 amd64
nvidia-open-560.35.05/unknown 560.35.05-1 amd64
nvidia-open-560/unknown 560.35.05-1 amd64
nvidia-open/unknown 560.35.05-1 amd64
nvidia-opencl-common/unknown 560.35.05-1 amd64
nvidia-opencl-common/unknown 560.35.05-1 i386
nvidia-opencl-icd/unknown 560.35.05-1 amd64
nvidia-opencl-icd/unknown 560.35.05-1 i386
nvidia-persistenced/unknown 560.35.05-1 amd64
nvidia-powerd/unknown 560.35.05-1 amd64
nvidia-primus-vk-common/oldstable 1.6.1-1 amd64
nvidia-primus-vk-wrapper/oldstable 1.6.1-1 amd64
nvidia-settings-legacy-390xx/oldstable 390.144-1 amd64
nvidia-settings-tesla-418/oldstable 418.113-6 amd64
nvidia-settings-tesla-450/oldstable 450.119.03-1 amd64
nvidia-settings-tesla-460/oldstable 460.91.03-1 amd64
nvidia-settings-tesla-470/oldstable 470.141.03-1~deb11u1 amd64
nvidia-settings/unknown 560.35.05-1 amd64
nvidia-smi/unknown 560.35.05-1 amd64
nvidia-support/oldstable 20151021+13 amd64
nvidia-suspend-common/unknown 560.35.05-1 amd64
nvidia-vdpau-driver/unknown 560.35.05-1 amd64
nvidia-vdpau-driver/unknown 560.35.05-1 i386
nvidia-vulkan-common/unknown 560.35.05-1 amd64
nvidia-vulkan-common/unknown 560.35.05-1 i386
nvidia-vulkan-icd/unknown 560.35.05-1 amd64
nvidia-vulkan-icd/unknown 560.35.05-1 i386
nvidia-xconfig/unknown 560.35.05-1 amd64
primus-nvidia/oldstable 0~20150328-13 amd64
primus-vk-nvidia/oldstable 1.6.1-1 amd64
xserver-xorg-video-nvidia/unknown 560.35.05-1 amd64
```

</details>

<details><summary>Training logs</summary>

```text
(.venv) root@a77fd2165454:/workspaces/vits# python train.py -c configs/ljs_base.json -m ljs_base
[INFO] {'train': {'log_interval': 200, 'eval_interval': 1000, 'seed': 1234, 'epochs': 20000, 'learning_rate': 0.0002, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 64, 'fp16_run': True, 'lr_decay': 0.999875, 'segment_size': 8192, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0}, 'data': {'training_files': 'filelists/ljs_audio_text_train_filelist.txt.cleaned', 'validation_files': 'filelists/ljs_audio_text_val_filelist.txt.cleaned', 'text_cleaners': ['english_cleaners2'], 'max_wav_value': 32768.0, 'sampling_rate': 22050, 'filter_length': 1024, 'hop_length': 256, 'win_length': 1024, 'n_mel_channels': 80, 'mel_fmin': 0.0, 'mel_fmax': None, 'add_blank': True, 'n_speakers': 0, 'cleaned_text': True}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [8, 8, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'n_layers_q': 3, 'use_spectral_norm': False}, 'model_dir': './logs/ljs_base'}
Traceback (most recent call last):
  File "train.py", line 290, in <module>
    main()
  File "train.py", line 50, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "/workspaces/vits/.venv/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/workspaces/vits/.venv/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/workspaces/vits/.venv/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/workspaces/vits/.venv/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/workspaces/vits/train.py", line 99, in run
    net_g = DDP(net_g, device_ids=[rank])
  File "/workspaces/vits/.venv/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 333, in __init__
    self.broadcast_bucket_size)
  File "/workspaces/vits/.venv/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 549, in _distributed_broadcast_coalesced
    dist._broadcast_coalesced(self.process_group, tensors, buffer_size)
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:518, unhandled system error, NCCL version 2.4.8
```

</details>

-----

The _CUDA Toolkit_ is installed as instructed by [CUDA Toolkit 12.6 Update 3 Downloads](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Debian&target_version=11&target_type=deb_network). What _CUDA Toolkit_ version should I use for running this project?

> [!NOTE]
>
> On my **Windows host** system, I'm using currently latest _Python for Windows_ 3.12 (`v3.12.7`) + _CUDA Toolkit_ (`v12.6 Update 3`) + _CuDNN Library_ (`v9.5`) + _PyTorch_ (`v2.5.1+cu124`). Everything works as expected.
