### ISSUE TITLE
Can I train on a Vietnamese custom dataset? If yes, can you specify how to do it?

### ISSUE THREAD

**Issue by tuannvhust** [jaywalnut310/vits#59]
I got that issue when I train on a custom Vietnamese dataset. At first, I thought maybe some wav files on my dataset is corupted, but it's not? How can I solve this?

[INFO] {'train': {'log_interval': 200, 'eval_interval': 1000, 'seed': 1234, 'epochs': 20000, 'learning_rate': 0.0002, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 16, 'fp16_run': True, 'lr_decay': 0.999875, 'segment_size': 8192, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0}, 'data': {'training_files': 'filelists/viet_audio_text_train_filelist.txt.cleaned', 'validation_files': 'filelists/viet_audio_text_val_filelist.txt.cleaned', 'max_wav_value': 32768.0, 'text_cleaners': ['english_cleaners2'], 'sampling_rate': 22050, 'filter_length': 1024, 'hop_length': 256, 'win_length': 1024, 'n_mel_channels': 80, 'mel_fmin': 0.0, 'mel_fmax': None, 'add_blank': True, 'n_speakers': 0, 'cleaned_text': True}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [8, 8, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'n_layers_q': 3, 'use_spectral_norm': False}, 'model_dir': './logs/viet_base'}
Traceback (most recent call last):
  File "train.py", line 290, in <module>
    main()
  File "train.py", line 50, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/content/gdrive/.shortcut-targets-by-id/1FR_wE-NryBYYhwIzjEI52awuLJDEAFfV/vits/train.py", line 117, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler, [train_loader, eval_loader], logger, [writer, writer_eval])
  File "/content/gdrive/.shortcut-targets-by-id/1FR_wE-NryBYYhwIzjEI52awuLJDEAFfV/vits/train.py", line 137, in train_and_evaluate
    for batch_idx, (x, x_lengths, spec, spec_lengths, y, y_lengths) in enumerate(train_loader):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.7/dist-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
UnboundLocalError: Caught UnboundLocalError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/gdrive/.shortcut-targets-by-id/1FR_wE-NryBYYhwIzjEI52awuLJDEAFfV/vits/data_utils.py", line 94, in __getitem__
    return self.get_audio_text_pair(self.audiopaths_and_text[index])
  File "/content/gdrive/.shortcut-targets-by-id/1FR_wE-NryBYYhwIzjEI52awuLJDEAFfV/vits/data_utils.py", line 62, in get_audio_text_pair
    spec, wav = self.get_audio(audiopath)
  File "/content/gdrive/.shortcut-targets-by-id/1FR_wE-NryBYYhwIzjEI52awuLJDEAFfV/vits/data_utils.py", line 66, in get_audio
    audio, sampling_rate = load_wav_to_torch(filename)
  File "/content/gdrive/.shortcut-targets-by-id/1FR_wE-NryBYYhwIzjEI52awuLJDEAFfV/vits/utils.py", line 134, in load_wav_to_torch
    sampling_rate, data = read(full_path)
  File "/usr/local/lib/python3.7/dist-packages/scipy/io/wavfile.py", line 609, in read
    return fs, data
UnboundLocalError: local variable 'fs' referenced before assignment

**Comment by quangnh-2761** [comment]
the problem is definitely due to your wav file, since scipy cant open it properly. Try to do a scipy.io.wavfile.read for loop through your whole dataset to find corrupted one. Or maybe you put a wrong path to file list.

**Comment by tuannvhust** [comment]
@quangnh-2761 i found that scipy.io.wavefile.read can not read any files of my dataset. So, I use librosa.loads instead. The bug disappeared but Is that ok?

**Comment by quangnh-2761** [comment]
yes they are similar

**Comment by tuannvhust** [comment]
no, it turned out they are not similar. I have to convert my dataset using sox, then keep using scipy
