### ISSUE TITLE
windows monotonic_align problem!

### ISSUE THREAD

**Issue by SteveTanggithub** [jaywalnut310/vits#63]
(aligner) D:\code\vits-main\monotonic_align>python setup.py build_ext --inplace
running build_ext
building 'monotonic_align.core' extension
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\h\.conda\envs\aligner\lib\site-packages\numpy\core\include -IC:\Users\h\.conda\envs\aligner\include -IC:\Users\h\.conda\envs\aligner\include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include" -Iinclude\10.0.19041.0\ucrt "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt" /Tccore.c /Fobuild\temp.win32-3.8\Release\core.obj
core.c
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX86\x86\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\h\.conda\envs\aligner\libs /LIBPATH:C:\Users\h\.conda\envs\aligner\PCbuild\win32 "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\ATLMFC\lib\x86" "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\lib\x86" /LIBPATH:lib\10.0.19041.0\ucrt\x86 "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\ATLMFC\lib\x86" "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\lib\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.19041.0\\um\x86" /EXPORT:PyInit_core build\temp.win32-3.8\Release\core.obj /OUT:D:\code\vits-main\monotonic_align\monotonic_align\core.cp38-win_amd64.pyd /IMPLIB:build\temp.win32-3.8\Release\core.cp38-win_amd64.lib
  正在创建库 build\temp.win32-3.8\Release\core.cp38-win_amd64.lib 和对象 build\temp.win32-3.8\Release\core.cp38-win_amd64.exp
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyBaseObject_Type
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyExc_BufferError
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyObject_SetAttr
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyUnicode_InternFromString
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyCFunction_Type
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyOS_snprintf
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyThreadState_Get
core.obj : error LNK2001: 无法解析的外部符号 __imp___Py_CheckRecursionLimit
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyErr_SetObject
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyErr_GivenExceptionMatches
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyLong_AsUnsignedLong
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyObject_Malloc
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyErr_WarnEx
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyFunction_Type
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyFrame_New
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyLong_AsSsize_t
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyExc_DeprecationWarning
core.obj : error LNK2001: 无法解析的外部符号 __imp__PySlice_Type
core.obj : error LNK2001: 无法解析的外部符号 __imp___PyLong_AsByteArray
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyImport_ImportModuleLevelObject
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyErr_NormalizeException
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyErr_Occurred
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyLong_FromSsize_t
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyNumber_Remainder
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyObject_GenericGetAttr
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyTraceBack_Here
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyEval_SaveThread
core.obj : error LNK2001: 无法解析的外部符号 __imp___PyThreadState_UncheckedGet
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyExc_RuntimeError
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyObject_SetAttrString
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyLong_FromLong
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyObject_GC_UnTrack
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyObject_Hash
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyExc_UnboundLocalError
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyErr_SetNone
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyInterpreterState_GetID
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyLong_FromUnsignedLongLong
core.obj : error LNK2001: 无法解析的外部符号 __imp__Py_GetVersion
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyThread_allocate_lock
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyObject_GetAttr
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyLong_AsUnsignedLongLong
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyBytes_FromString
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyGILState_Release
core.obj : error LNK2001: 无法解析的外部符号 __imp___Py_NoneStruct
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyLong_AsLongLong
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyTuple_New
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyDict_SetItemString
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyDict_Size
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyLong_FromLongLong
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyThread_acquire_lock
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyFrame_Type
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyFloat_FromDouble
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyExc_AttributeError
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyNumber_Multiply
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyErr_SetString
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyExc_ZeroDivisionError
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyObject_GetIter
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyNumber_Add
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyErr_WarnFormat
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyEval_EvalCodeEx
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyExc_ValueError
core.obj : error LNK2001: 无法解析的外部符号 __imp___Py_CheckRecursiveCall
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyLong_FromUnsignedLong
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyDict_Next
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyErr_Format
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyObject_RichCompare
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyTuple_Type
core.obj : error LNK2001: 无法解析的外部符号 __imp___Py_FalseStruct
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyNumber_InPlaceAdd
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyFloat_Type
core.obj : error LNK2001: 无法解析的外部符号 __imp___PyLong_FromByteArray
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyModule_NewObject
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyMethod_Type
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyLong_Type
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyErr_Restore
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyExc_OverflowError
core.obj : error LNK2001: 无法解析的外部符号 __imp___Py_Dealloc
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyImport_GetModuleDict
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyModule_GetDict
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyObject_Free
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyErr_ExceptionMatches
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyThread_release_lock
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyErr_Fetch
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyLong_AsLong
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyObject_Not
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyUnicode_FromFormat
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyObject_GetBuffer
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyNumber_InPlaceMultiply
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyList_New
core.obj : error LNK2001: 无法解析的外部符号 __imp__PySlice_New
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyImport_AddModule
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyType_Ready
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyObject_GetAttrString
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyErr_Clear
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyList_Append
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyBytes_Type
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyObject_RichCompareBool
core.obj : error LNK2001: 无法解析的外部符号 __imp__Py_FatalError
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyUnicode_Decode
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyCode_New
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyException_SetTraceback
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyCapsule_New
core.obj : error LNK2001: 无法解析的外部符号 __imp___PyObject_GenericGetAttrWithDict
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyDict_SetItem
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyDict_New
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyUnicode_Type
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyThread_free_lock
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyObject_CallFinalizerFromDealloc
core.obj : error LNK2001: 无法解析的外部符号 __imp___PyDict_GetItem_KnownHash
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyNumber_Index
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyMem_Free
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyExc_StopIteration
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyList_Type
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyErr_NoMemory
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyDict_GetItemString
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyObject_GetItem
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyObject_CallObject
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyEval_InitThreads
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyModuleDef_Init
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyObject_GC_Track
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyBytes_FromStringAndSize
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyExc_NotImplementedError
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyGILState_Ensure
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyDict_DelItem
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyUnicode_Compare
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyObject_IsSubclass
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyExc_TypeError
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyMem_Realloc
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyCFunction_NewEx
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyObject_IsTrue
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyExc_NameError
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyTuple_Pack
core.obj : error LNK2001: 无法解析的外部符号 __imp__Py_OptimizeFlag
core.obj : error LNK2001: 无法解析的外部符号 __imp___PyUnicode_Ready
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyMem_Malloc
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyList_AsTuple
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyExc_IndexError
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyExc_ImportError
core.obj : error LNK2001: 无法解析的外部符号 __imp___Py_TrueStruct
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyUnicode_DecodeASCII
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyExc_SystemError
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyExc_AssertionError
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyObject_SetItem
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyException_SetCause
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyType_Modified
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyTraceBack_Type
core.obj : error LNK2001: 无法解析的外部符号 __imp___PyList_Extend
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyEval_EvalFrameEx
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyUnicode_FromString
core.obj : error LNK2001: 无法解析的外部符号 __imp___PyType_Lookup
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyUnicode_Format
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyObject_Size
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyBuffer_Release
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyObject_Call
core.obj : error LNK2001: 无法解析的外部符号 __imp__PySequence_Tuple
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyEval_RestoreThread
core.obj : error LNK2001: 无法解析的外部符号 __imp__PyUnicode_FromStringAndSize
core.obj : error LNK2001: 无法解析的外部符号 __imp___PyObject_GetDictPtr
D:\code\vits-main\monotonic_align\monotonic_align\core.cp38-win_amd64.pyd : fatal error LNK1120: 158 个无法解析的外部命令
error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX86\\x86\\link.exe' failed with exit status 1120

**Comment by Aloento** [comment]
说实话不推荐用WIN来干这玩意，然后这个问题是你自己环境没配好，不是VITS的问题

**Comment by meteorlin** [comment]
将`monotonic_align/core.pyx`中的有效代码转移到项目根目录新创建的`monotonic_align.py`文件，并将原来的`monotonic_align`文件夹删除或重命名为其他名字即可。（这一操作取消了并行性）`monotonic_align.py`文件内容如下：
```python
import numpy as np
import torch

def maximum_path_c(path, value, t_y, t_x, max_neg_val=-1e9):
  for y in range(t_y):
    for x in range(max(0, t_x + y - t_y), min(t_x, y + 1)):
      if x == y:
        v_cur = max_neg_val
      else:
        v_cur = value[y-1, x]
      if x == 0:
        if y == 0:
          v_prev = 0.
        else:
          v_prev = max_neg_val
      else:
        v_prev = value[y-1, x-1]
      value[y, x] += max(v_prev, v_cur)

  for y in range(t_y - 1, -1, -1):
    path[y, index] = 1
    if index != 0 and (index == y or value[y-1, index] < value[y-1, index-1]):
      index = index - 1


def maximum_path(neg_cent, mask):
  """ Cython optimized version.
  neg_cent: [b, t_t, t_s]
  mask: [b, t_t, t_s]
  """
  device = neg_cent.device
  dtype = neg_cent.dtype
  neg_cent = neg_cent.data.cpu().numpy().astype(np.float32)
  path = np.zeros(neg_cent.shape, dtype=np.int32)

  t_t_max = mask.sum(1)[:, 0].data.cpu().numpy().astype(np.int32)
  t_s_max = mask.sum(2)[:, 0].data.cpu().numpy().astype(np.int32)
  maximum_path_c(path, neg_cent, t_t_max, t_s_max)
  return torch.from_numpy(path).to(device=device, dtype=dtype)
```

**Comment by mentlesoul** [comment]
> 
我如果尝试build monotonic_align的话会有这个报错
Compiling core.pyx because it changed.
[1/1] Cythonizing core.pyx
E:\Environments\anaconda3\envs\Jarvis\lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: F:\Jupyter\Jarvis\vits-Cjang\monotonic_align\core.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
core.c
E:\Environments\anaconda3\envs\Jarvis\include\pyconfig.h(59): fatal error C1083: 无法打开包括文件: “io.h”: No such file or directory
error: command 'E:\\Environments\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

用你说的这个py文件的话会有这个报错：
Traceback (most recent call last):
  File "train.py", line 301, in <module>
    main()
  File "train.py", line 55, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "E:\Environments\anaconda3\envs\Jarvis\lib\site-packages\torch\multiprocessing\spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "E:\Environments\anaconda3\envs\Jarvis\lib\site-packages\torch\multiprocessing\spawn.py", line 198, in start_processes
    while not context.join():
  File "E:\Environments\anaconda3\envs\Jarvis\lib\site-packages\torch\multiprocessing\spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "E:\Environments\anaconda3\envs\Jarvis\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "F:\Jupyter\Jarvis\vits-Cjang\train.py", line 122, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler, [train_loader, eval_loader], logger, [writer, writer_eval])
  File "F:\Jupyter\Jarvis\vits-Cjang\train.py", line 149, in train_and_evaluate
    (z, z_p, m_p, logs_p, m_q, logs_q) = net_g(x, x_lengths, spec, spec_lengths)
  File "E:\Environments\anaconda3\envs\Jarvis\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Environments\anaconda3\envs\Jarvis\lib\site-packages\torch\nn\parallel\distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "E:\Environments\anaconda3\envs\Jarvis\lib\site-packages\torch\nn\parallel\distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "E:\Environments\anaconda3\envs\Jarvis\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\Jupyter\Jarvis\vits-Cjang\models.py", line 480, in forward
    attn = monotonic_align.maximum_path(neg_cent, attn_mask.squeeze(1)).unsqueeze(1).detach()
  File "F:\Jupyter\Jarvis\vits-Cjang\monotonic_align.py", line 38, in maximum_path
    maximum_path_c(path, neg_cent, t_t_max, t_s_max)
  File "F:\Jupyter\Jarvis\vits-Cjang\monotonic_align.py", line 5, in maximum_path_c
    for y in range(t_y):
TypeError: only integer scalar arrays can be converted to a scalar index

请教一下如何解决，非常感谢

**Comment by hunter2009pf** [comment]
> 将`monotonic_align/core.pyx`中的有效代码转移到项目根目录新创建的`monotonic_align.py`文件，并将原来的`monotonic_align`文件夹删除或重命名为其他名字即可。（这一操作取消了并行性）`monotonic_align.py`文件内容如下：
> 
> ```python
> import numpy as np
> import torch
> 
> def maximum_path_c(path, value, t_y, t_x, max_neg_val=-1e9):
>   for y in range(t_y):
>     for x in range(max(0, t_x + y - t_y), min(t_x, y + 1)):
>       if x == y:
>         v_cur = max_neg_val
>       else:
>         v_cur = value[y-1, x]
>       if x == 0:
>         if y == 0:
>           v_prev = 0.
>         else:
>           v_prev = max_neg_val
>       else:
>         v_prev = value[y-1, x-1]
>       value[y, x] += max(v_prev, v_cur)
> 
>   for y in range(t_y - 1, -1, -1):
>     path[y, index] = 1
>     if index != 0 and (index == y or value[y-1, index] < value[y-1, index-1]):
>       index = index - 1
> 
> 
> def maximum_path(neg_cent, mask):
>   """ Cython optimized version.
>   neg_cent: [b, t_t, t_s]
>   mask: [b, t_t, t_s]
>   """
>   device = neg_cent.device
>   dtype = neg_cent.dtype
>   neg_cent = neg_cent.data.cpu().numpy().astype(np.float32)
>   path = np.zeros(neg_cent.shape, dtype=np.int32)
> 
>   t_t_max = mask.sum(1)[:, 0].data.cpu().numpy().astype(np.int32)
>   t_s_max = mask.sum(2)[:, 0].data.cpu().numpy().astype(np.int32)
>   maximum_path_c(path, neg_cent, t_t_max, t_s_max)
>   return torch.from_numpy(path).to(device=device, dtype=dtype)
> ```

you are really awesome!

**Comment by Aydous** [comment]
> 将`monotonic_align/core.pyx`中的有效代码转移到项目根目录新创建的`monotonic_align.py`文件，并将原来的`monotonic_align`文件夹删除或重命名为其他名字即可。（这一操作取消了并行性）`monotonic_align.py`文件内容如下：
> 
> ```python
> import numpy as np
> import torch
> 
> def maximum_path_c(path, value, t_y, t_x, max_neg_val=-1e9):
>   for y in range(t_y):
>     for x in range(max(0, t_x + y - t_y), min(t_x, y + 1)):
>       if x == y:
>         v_cur = max_neg_val
>       else:
>         v_cur = value[y-1, x]
>       if x == 0:
>         if y == 0:
>           v_prev = 0.
>         else:
>           v_prev = max_neg_val
>       else:
>         v_prev = value[y-1, x-1]
>       value[y, x] += max(v_prev, v_cur)
> 
>   for y in range(t_y - 1, -1, -1):
>     path[y, index] = 1
>     if index != 0 and (index == y or value[y-1, index] < value[y-1, index-1]):
>       index = index - 1
> 
> 
> def maximum_path(neg_cent, mask):
>   """ Cython optimized version.
>   neg_cent: [b, t_t, t_s]
>   mask: [b, t_t, t_s]
>   """
>   device = neg_cent.device
>   dtype = neg_cent.dtype
>   neg_cent = neg_cent.data.cpu().numpy().astype(np.float32)
>   path = np.zeros(neg_cent.shape, dtype=np.int32)
> 
>   t_t_max = mask.sum(1)[:, 0].data.cpu().numpy().astype(np.int32)
>   t_s_max = mask.sum(2)[:, 0].data.cpu().numpy().astype(np.int32)
>   maximum_path_c(path, neg_cent, t_t_max, t_s_max)
>   return torch.from_numpy(path).to(device=device, dtype=dtype)
> ```

我在Linux上也遇到了类似的问题，用了你的方法后就解决了，请问这个方法是把调用cpp的代码变成直接调用python吗？作者额外调用cpp是为了提升MAS的效率吗
