### ISSUE TITLE
RuntimeError: "fill_cuda" not implemented for 'ComplexHalf'

### ISSUE THREAD

**Issue by longglecc** [jaywalnut310/vits#65]
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/gaol/anaconda3/envs/mtts/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/gaol/codes/Voices/vits_chinese/train.py", line 119, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler, [train_loader, eval_loader], logger, [writer, writer_eval])
  File "/home/gaol/codes/Voices/vits_chinese/train.py", line 192, in train_and_evaluate
    scaler.scale(loss_gen_all).backward()
  File "/home/gaol/anaconda3/envs/mtts/lib/python3.6/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/gaol/anaconda3/envs/mtts/lib/python3.6/site-packages/torch/autograd/__init__.py", line 147, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: "fill_cuda" not implemented for 'ComplexHalf'

**Comment by longglecc** [comment]
"fp16_run": false

**Comment by longglecc** [comment]
"fp16_run": false ，It is works

**Comment by liumingda** [comment]
great，thank you!
