### ISSUE TITLE
Error on tensor size & How to config with 16KHz waves?

### ISSUE THREAD

**Issue by voxServalG** [jaywalnut310/vits#90]
Hi, I use custom dataset with 16bit PCM 16KHz waves.Here is my configs

`{
  "train": {
    "log_interval": 200,
    "eval_interval": 1000,
    "seed": 1234,
    "epochs": 20000,
    "learning_rate": 2e-4,
    "betas": [0.8, 0.99],
    "eps": 1e-9,
    "batch_size": 8,
    "fp16_run": false,
    "lr_decay": 0.999875,
    "segment_size": 7872,
    "init_lr_ratio": 1,
    "warmup_epochs": 0,
    "c_mel": 45,
    "c_kl": 1.0
  },
  "data": {
    "training_files":"filelists/ljs_audio_text_train_filelist.txt",
    "validation_files":"filelists/ljs_audio_text_val_filelist.txt",
    "text_cleaners":["basic_cleaners"],
    "max_wav_value": 32768.0,
    "sampling_rate": 16000,
    "filter_length": 1024,
    "hop_length": 256,
    "win_length": 1024,
    "n_mel_channels": 80,
    "mel_fmin": 0.0,
    "mel_fmax": null,
    "add_blank": true,
    "n_speakers": 0,
    "cleaned_text": true
  },
  "model": {
    "inter_channels": 192,
    "hidden_channels": 192,
    "filter_channels": 768,
    "n_heads": 2,
    "n_layers": 6,
    "kernel_size": 3,
    "p_dropout": 0.1,
    "resblock": "1",
    "resblock_kernel_sizes": [3,7,11],
    "resblock_dilation_sizes": [[1,3,5], [1,3,5], [1,3,5]],
    "upsample_rates": [8,8,2,2],
    "upsample_initial_channel": 512,
    "upsample_kernel_sizes": [16,16,4,4],
    "n_layers_q": 3,
    "use_spectral_norm": false
  }
}`

when I ran train.py, such error happened

`[INFO] {'train': {'log_interval': 200, 'eval_interval': 1000, 'seed': 1234, 'epochs': 20000, 'learning_rate': 0.0002, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 8, 'fp16_run': False, 'lr_decay': 0.999875, 'segment_size': 8192, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0}, 'data': {'training_files': 'filelists/ljs_audio_text_train_filelist.txt', 'validation_files': 'filelists/ljs_audio_text_val_filelist.txt', 'text_cleaners': ['basic_cleaners'], 'max_wav_value': 32768.0, 'sampling_rate': 16000, 'filter_length': 1024, 'hop_length': 256, 'win_length': 1024, 'n_mel_channels': 80, 'mel_fmin': 0.0, 'mel_fmax': None, 'add_blank': True, 'n_speakers': 0, 'cleaned_text': True}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [8, 8, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'n_layers_q': 3, 'use_spectral_norm': False}, 'model_dir': './logs\\ljs_base'}
./logs\ljs_base\G_0.pth
[INFO] Loaded checkpoint './logs\ljs_base\G_0.pth' (iteration 1)
./logs\ljs_base\D_0.pth
[INFO] Loaded checkpoint './logs\ljs_base\D_0.pth' (iteration 1)
C:\Users\randm\miniconda3\envs\vits\lib\site-packages\torch\functional.py:581: UserWarning: stft will soon require the return_complex parameter be given for real inputs, and will further require that return_complex=True in a future PyTorch release. (Triggered internally at  ..\aten\src\ATen\native\SpectralOps.cpp:639.)
  normalized, onesided, return_complex)
[INFO] Train Epoch: 1 [0%]
[INFO] [3.3916234970092773, 0.9196377992630005, 0.5174797177314758, 59.94203567504883, 1.200174331665039, 70.09718322753906, 0, 0.0002]
[INFO] Saving model and optimizer state at iteration 1 to ./logs\ljs_base\G_0.pth
[INFO] Saving model and optimizer state at iteration 1 to ./logs\ljs_base\D_0.pth
Traceback (most recent call last):
  File "train.py", line 290, in <module>
    main()
  File "train.py", line 50, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "C:\Users\randm\miniconda3\envs\vits\lib\site-packages\torch\multiprocessing\spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "C:\Users\randm\miniconda3\envs\vits\lib\site-packages\torch\multiprocessing\spawn.py", line 188, in start_processes
    while not context.join():
  File "C:\Users\randm\miniconda3\envs\vits\lib\site-packages\torch\multiprocessing\spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "C:\Users\randm\miniconda3\envs\vits\lib\site-packages\torch\multiprocessing\spawn.py", line 59, in _wrap
    fn(i, *args)
  File "D:\TRAINING\vits\train.py", line 117, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler, [train_loader, eval_loader], logger, [writer, writer_eval])
  File "D:\TRAINING\vits\train.py", line 165, in train_and_evaluate
    y = commons.slice_segments(y, ids_slice * hps.data.hop_length, hps.train.segment_size) # slice
  File "D:\TRAINING\vits\commons.py", line 53, in slice_segments
    ret[i] = x[i, :, idx_str:idx_end]
RuntimeError: The expanded size of the tensor (8192) must match the existing size (2786) at non-singleton dimension 1.  Target sizes: [1, 8192].  Tensor sizes: [2786]`

Is this error due to dataset's sample rate(16KHz instead of 22.05KHz)? What adjustment should I make to continue the training? Thanks in advance.

**Comment by voxServalG** [comment]
Please inform if further infomation required.

**Comment by makerjackie** [comment]
do you remove `.spec.pt` file after you change sample_rate, ps: segment_size should be divisible by hop_size

https://github.com/jaywalnut310/vits/blob/2e561ba58618d021b5b8323d3765880f7e0ecfdb/data_utils.py#L72-L80
